//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalBookKeeper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalBookKeeper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal BookKeeper.
        /// </summary>
        internal static string strAppTitle {
            get {
                return ResourceManager.GetString("strAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Schedule.
        /// </summary>
        internal static string strBtnAdd2Schedule {
            get {
                return ResourceManager.GetString("strBtnAdd2Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        internal static string strBtnAddAccount {
            get {
                return ResourceManager.GetString("strBtnAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        internal static string strBtnAddCategory {
            get {
                return ResourceManager.GetString("strBtnAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Currency.
        /// </summary>
        internal static string strBtnAddCurrency {
            get {
                return ResourceManager.GetString("strBtnAddCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Schedule.
        /// </summary>
        internal static string strBtnAddSchedule {
            get {
                return ResourceManager.GetString("strBtnAddSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Transaction.
        /// </summary>
        internal static string strBtnAddTransaction {
            get {
                return ResourceManager.GetString("strBtnAddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Types.
        /// </summary>
        internal static string strBtnAddTypes {
            get {
                return ResourceManager.GetString("strBtnAddTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string strBtnDelAccount {
            get {
                return ResourceManager.GetString("strBtnDelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Schedule.
        /// </summary>
        internal static string strBtnDelSchedule {
            get {
                return ResourceManager.GetString("strBtnDelSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Transaction.
        /// </summary>
        internal static string strBtnDelTransaction {
            get {
                return ResourceManager.GetString("strBtnDelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Account.
        /// </summary>
        internal static string strBtnModAccount {
            get {
                return ResourceManager.GetString("strBtnModAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Category.
        /// </summary>
        internal static string strBtnModCategory {
            get {
                return ResourceManager.GetString("strBtnModCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Currency.
        /// </summary>
        internal static string strBtnModCurrency {
            get {
                return ResourceManager.GetString("strBtnModCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Schedule.
        /// </summary>
        internal static string strBtnModSchedule {
            get {
                return ResourceManager.GetString("strBtnModSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Types.
        /// </summary>
        internal static string strBtnModTypes {
            get {
                return ResourceManager.GetString("strBtnModTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string strBtnRefresh {
            get {
                return ResourceManager.GetString("strBtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Transaction.
        /// </summary>
        internal static string strBtnRunSchedule {
            get {
                return ResourceManager.GetString("strBtnRunSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Balance of Account to Be Deleted SHOULD Be 0!.
        /// </summary>
        internal static string strErrAccountBalanceNot0 {
            get {
                return ResourceManager.GetString("strErrAccountBalanceNot0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acronym SHOULD NOT Be Blank!.
        /// </summary>
        internal static string strErrAcronymBlank {
            get {
                return ResourceManager.GetString("strErrAcronymBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount In SHOULD NOT Be Blank When Category is Transfer or Income!.
        /// </summary>
        internal static string strErrAmountInBlank {
            get {
                return ResourceManager.GetString("strErrAmountInBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Out SHOULD NOT Be Blank When Category is Transfer or Outcome!.
        /// </summary>
        internal static string strErrAmountOutBlank {
            get {
                return ResourceManager.GetString("strErrAmountOutBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Balance of Account SHOULD NOT Be Blank!.
        /// </summary>
        internal static string strErrBalanceBlank {
            get {
                return ResourceManager.GetString("strErrBalanceBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency of Account SHOULD Be Assigned!.
        /// </summary>
        internal static string strErrCurrencyNotAssigned {
            get {
                return ResourceManager.GetString("strErrCurrencyNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Schema NOT Matching, Application Terminated!.
        /// </summary>
        internal static string strErrDbSchema {
            get {
                return ResourceManager.GetString("strErrDbSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Point SHOULD Be 0, 1, 2 or 3!.
        /// </summary>
        internal static string strErrInvalidDecPoint {
            get {
                return ResourceManager.GetString("strErrInvalidDecPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Month Value Set When Using Customized Query!.
        /// </summary>
        internal static string strErrMonthInvalid {
            get {
                return ResourceManager.GetString("strErrMonthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name SHOULD NOT Be Blank!.
        /// </summary>
        internal static string strErrNameBlank {
            get {
                return ResourceManager.GetString("strErrNameBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Account to Be Deleted!.
        /// </summary>
        internal static string strErrNoAccount2Delete {
            get {
                return ResourceManager.GetString("strErrNoAccount2Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Account to Be Modified!.
        /// </summary>
        internal static string strErrNoAccount2Modify {
            get {
                return ResourceManager.GetString("strErrNoAccount2Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category SHOULD Be Assigned Before Adding a Transaction!.
        /// </summary>
        internal static string strErrNoCategoryAssigned {
            get {
                return ResourceManager.GetString("strErrNoCategoryAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Category to Be Modified!.
        /// </summary>
        internal static string strErrNoCategorySelected {
            get {
                return ResourceManager.GetString("strErrNoCategorySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS-SQL DB or Server NOT Installed, Application Terminated!.
        /// </summary>
        internal static string strErrNoDb {
            get {
                return ResourceManager.GetString("strErrNoDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Account SHOULD Be Assigned When Category is Transfer or Income!.
        /// </summary>
        internal static string strErrNoDstAccount {
            get {
                return ResourceManager.GetString("strErrNoDstAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Set Transaction Category as &apos;Income&apos;, &apos;Transfer&apos; or &apos;Outcome&apos;!.
        /// </summary>
        internal static string strErrNoFlowDirectSelected {
            get {
                return ResourceManager.GetString("strErrNoFlowDirectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Schedule to Be Deleted!.
        /// </summary>
        internal static string strErrNoSchedule2Delete {
            get {
                return ResourceManager.GetString("strErrNoSchedule2Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Schedule to Make Transaction!.
        /// </summary>
        internal static string strErrNoSchedule2MakeTransaction {
            get {
                return ResourceManager.GetString("strErrNoSchedule2MakeTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Schedule to Be Modified!.
        /// </summary>
        internal static string strErrNoSchedule2Modify {
            get {
                return ResourceManager.GetString("strErrNoSchedule2Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Account SHOULD Be Assigned When Category is Transfer or Outcome!.
        /// </summary>
        internal static string strErrNoSrcAccount {
            get {
                return ResourceManager.GetString("strErrNoSrcAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Transaction to Be Added to Schedules!.
        /// </summary>
        internal static string strErrNoTransaction2Add2Schedule {
            get {
                return ResourceManager.GetString("strErrNoTransaction2Add2Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Transaction to Be Deleted!.
        /// </summary>
        internal static string strErrNoTransaction2Delete {
            get {
                return ResourceManager.GetString("strErrNoTransaction2Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Set Account Type as &apos;Assets&apos; or &apos;Liabilities&apos;!.
        /// </summary>
        internal static string strErrNoTypeFlagSelected {
            get {
                return ResourceManager.GetString("strErrNoTypeFlagSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Account Type to Be Modified!.
        /// </summary>
        internal static string strErrNoTypeSelected {
            get {
                return ResourceManager.GetString("strErrNoTypeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period (in Day) SHOULD NOT Be Blank!.
        /// </summary>
        internal static string strErrPeriodBlank {
            get {
                return ResourceManager.GetString("strErrPeriodBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Period (in Day), SHOULD Be Between 7 &amp; 365!.
        /// </summary>
        internal static string strErrPeriodInvalid {
            get {
                return ResourceManager.GetString("strErrPeriodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could NOT Tab Out When Editing in Current Tab!.
        /// </summary>
        internal static string StrErrTabLock {
            get {
                return ResourceManager.GetString("StrErrTabLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string strErrTitle {
            get {
                return ResourceManager.GetString("strErrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type SHOULD Be Assigned!.
        /// </summary>
        internal static string strErrTypeNotAssigned {
            get {
                return ResourceManager.GetString("strErrTypeNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Year Value (Not Between 2000 &amp; 2099) Set When Using Customized Query!.
        /// </summary>
        internal static string strErrYearInvalid {
            get {
                return ResourceManager.GetString("strErrYearInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Value SHOULD Be Set (Month Value is Optional) When Using Customized Query!.
        /// </summary>
        internal static string strErrYearNotSet {
            get {
                return ResourceManager.GetString("strErrYearNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Modify the Main Currency, Want to Keep Existing Main Currency Setting?.
        /// </summary>
        internal static string strHintConfirmKeepMainCurrency {
            get {
                return ResourceManager.GetString("strHintConfirmKeepMainCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Main Currency Setting in System, Want the Added Currency to be Set as Main Currency?.
        /// </summary>
        internal static string strHintConfirmMainCurrency {
            get {
                return ResourceManager.GetString("strHintConfirmMainCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Reset the Main Currency, Want to Keep Existing Main Currency Setting?.
        /// </summary>
        internal static string strHintConfirmNotClearMainCurrency {
            get {
                return ResourceManager.GetString("strHintConfirmNotClearMainCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Main Currency WILL Overwrite Main Currency Setting in System, Want to Overwrite?.
        /// </summary>
        internal static string strHintConfirmOverwriteMainCurrency {
            get {
                return ResourceManager.GetString("strHintConfirmOverwriteMainCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Field(s) in &quot;{0}&quot; and &quot;{1}&quot; Table to Activate &quot;{2}&quot; Tab!.
        /// </summary>
        internal static string strHintForTabs {
            get {
                return ResourceManager.GetString("strHintForTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Existing Currency to Be Modified!.
        /// </summary>
        internal static string strHintModCurrency {
            get {
                return ResourceManager.GetString("strHintModCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        internal static string strHintTitle {
            get {
                return ResourceManager.GetString("strHintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to Make Transaction Using Selected Schedule?.
        /// </summary>
        internal static string strHintTransactionFromSchedule {
            get {
                return ResourceManager.GetString("strHintTransactionFromSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string strTabAccount {
            get {
                return ResourceManager.GetString("strTabAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string strTabCategory {
            get {
                return ResourceManager.GetString("strTabCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string strTabCurrency {
            get {
                return ResourceManager.GetString("strTabCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Tab.
        /// </summary>
        internal static string strTabMain {
            get {
                return ResourceManager.GetString("strTabMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        internal static string strTabSchedule {
            get {
                return ResourceManager.GetString("strTabSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string strTabTransaction {
            get {
                return ResourceManager.GetString("strTabTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Types.
        /// </summary>
        internal static string strTabType {
            get {
                return ResourceManager.GetString("strTabType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts in DB.
        /// </summary>
        internal static string strTxtAccounts {
            get {
                return ResourceManager.GetString("strTxtAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        internal static string strTxtAccountType {
            get {
                return ResourceManager.GetString("strTxtAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Types in DB.
        /// </summary>
        internal static string strTxtAccountTypes {
            get {
                return ResourceManager.GetString("strTxtAccountTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acronym.
        /// </summary>
        internal static string strTxtAcronym {
            get {
                return ResourceManager.GetString("strTxtAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to Add Sub-Vategory of Current Selected Category? (Click &apos;No&apos; to Add Root Category).
        /// </summary>
        internal static string strTxtAddSubCategory {
            get {
                return ResourceManager.GetString("strTxtAddSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to Add Sub-Type of Current Selected Type? (Click &apos;No&apos; to Add Root Type).
        /// </summary>
        internal static string strTxtAddSubTypes {
            get {
                return ResourceManager.GetString("strTxtAddSubTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Schedules.
        /// </summary>
        internal static string strTxtAllSchedules {
            get {
                return ResourceManager.GetString("strTxtAllSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount In.
        /// </summary>
        internal static string strTxtAmountIn {
            get {
                return ResourceManager.GetString("strTxtAmountIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Out.
        /// </summary>
        internal static string strTxtAmountOut {
            get {
                return ResourceManager.GetString("strTxtAmountOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        internal static string strTxtAssets {
            get {
                return ResourceManager.GetString("strTxtAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string strTxtBalance {
            get {
                return ResourceManager.GetString("strTxtBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string strTxtCancel {
            get {
                return ResourceManager.GetString("strTxtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Add.
        /// </summary>
        internal static string strTxtCancelAdd {
            get {
                return ResourceManager.GetString("strTxtCancelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Modify.
        /// </summary>
        internal static string strTxtCancelMod {
            get {
                return ResourceManager.GetString("strTxtCancelMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Categories in DB.
        /// </summary>
        internal static string strTxtCategories {
            get {
                return ResourceManager.GetString("strTxtCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string strTxtCategory {
            get {
                return ResourceManager.GetString("strTxtCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change in Assets.
        /// </summary>
        internal static string strTxtChangeAssets {
            get {
                return ResourceManager.GetString("strTxtChangeAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change in Liabilities.
        /// </summary>
        internal static string strTxtChangeLiabilities {
            get {
                return ResourceManager.GetString("strTxtChangeLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string strTxtConfirm {
            get {
                return ResourceManager.GetString("strTxtConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Add.
        /// </summary>
        internal static string strTxtConfirmAdd {
            get {
                return ResourceManager.GetString("strTxtConfirmAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Modify.
        /// </summary>
        internal static string strTxtConfirmMod {
            get {
                return ResourceManager.GetString("strTxtConfirmMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Time.
        /// </summary>
        internal static string strTxtCreatedTime {
            get {
                return ResourceManager.GetString("strTxtCreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies in DB.
        /// </summary>
        internal static string strTxtCurrencies {
            get {
                return ResourceManager.GetString("strTxtCurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string strTxtCurrency {
            get {
                return ResourceManager.GetString("strTxtCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string strTxtCustomize {
            get {
                return ResourceManager.GetString("strTxtCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Point.
        /// </summary>
        internal static string strTxtDecPoint {
            get {
                return ResourceManager.GetString("strTxtDecPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string strTxtDescription {
            get {
                return ResourceManager.GetString("strTxtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Account.
        /// </summary>
        internal static string strTxtDstAccount {
            get {
                return ResourceManager.GetString("strTxtDstAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Schedules.
        /// </summary>
        internal static string strTxtDueSchedules {
            get {
                return ResourceManager.GetString("strTxtDueSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equity.
        /// </summary>
        internal static string strTxtEquity {
            get {
                return ResourceManager.GetString("strTxtEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashflow Direction.
        /// </summary>
        internal static string strTxtFlowDirect {
            get {
                return ResourceManager.GetString("strTxtFlowDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string strTxtIncome {
            get {
                return ResourceManager.GetString("strTxtIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Main Currency?.
        /// </summary>
        internal static string strTxtIsMainCurrency {
            get {
                return ResourceManager.GetString("strTxtIsMainCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Made Time.
        /// </summary>
        internal static string strTxtLastMade {
            get {
                return ResourceManager.GetString("strTxtLastMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        internal static string strTxtLastMonth {
            get {
                return ResourceManager.GetString("strTxtLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        internal static string strTxtLastYear {
            get {
                return ResourceManager.GetString("strTxtLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liabilities.
        /// </summary>
        internal static string strTxtLiabilities {
            get {
                return ResourceManager.GetString("strTxtLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made Time.
        /// </summary>
        internal static string strTxtMadeTime {
            get {
                return ResourceManager.GetString("strTxtMadeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string strTxtMonth {
            get {
                return ResourceManager.GetString("strTxtMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string strTxtName {
            get {
                return ResourceManager.GetString("strTxtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string strTxtNameAccount {
            get {
                return ResourceManager.GetString("strTxtNameAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type Name.
        /// </summary>
        internal static string strTxtNameAccountType {
            get {
                return ResourceManager.GetString("strTxtNameAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string strTxtNameCategory {
            get {
                return ResourceManager.GetString("strTxtNameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name.
        /// </summary>
        internal static string strTxtNameCurrency {
            get {
                return ResourceManager.GetString("strTxtNameCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Name.
        /// </summary>
        internal static string strTxtNameSchedule {
            get {
                return ResourceManager.GetString("strTxtNameSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Name.
        /// </summary>
        internal static string strTxtNameTransaction {
            get {
                return ResourceManager.GetString("strTxtNameTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Cash Flow.
        /// </summary>
        internal static string strTxtNetCashflow {
            get {
                return ResourceManager.GetString("strTxtNetCashflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        internal static string strTxtOutcome {
            get {
                return ResourceManager.GetString("strTxtOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period in Day.
        /// </summary>
        internal static string strTxtPeriodInDay {
            get {
                return ResourceManager.GetString("strTxtPeriodInDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the Time to Make Scheduled Transaction!.
        /// </summary>
        internal static string strTxtPickTransactionTime {
            get {
                return ResourceManager.GetString("strTxtPickTransactionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules in DB.
        /// </summary>
        internal static string strTxtSchedules {
            get {
                return ResourceManager.GetString("strTxtSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Selected as Main Currency.
        /// </summary>
        internal static string strTxtSetMainCurrency {
            get {
                return ResourceManager.GetString("strTxtSetMainCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Account.
        /// </summary>
        internal static string strTxtSrcAccount {
            get {
                return ResourceManager.GetString("strTxtSrcAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        internal static string strTxtThisMonth {
            get {
                return ResourceManager.GetString("strTxtThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        internal static string strTxtThisYear {
            get {
                return ResourceManager.GetString("strTxtThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string strTxtTitleBalance {
            get {
                return ResourceManager.GetString("strTxtTitleBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashflow.
        /// </summary>
        internal static string strTxtTitleCashflow {
            get {
                return ResourceManager.GetString("strTxtTitleCashflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cash Inflows.
        /// </summary>
        internal static string strTxtTotalInflows {
            get {
                return ResourceManager.GetString("strTxtTotalInflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cash Outflows.
        /// </summary>
        internal static string strTxtTotalOutflows {
            get {
                return ResourceManager.GetString("strTxtTotalOutflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions in DB.
        /// </summary>
        internal static string strTxtTransactions {
            get {
                return ResourceManager.GetString("strTxtTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string strTxtTransfer {
            get {
                return ResourceManager.GetString("strTxtTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string strTxtTypeFlags {
            get {
                return ResourceManager.GetString("strTxtTypeFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Time.
        /// </summary>
        internal static string strTxtUpdatedTime {
            get {
                return ResourceManager.GetString("strTxtUpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string strTxtYear {
            get {
                return ResourceManager.GetString("strTxtYear", resourceCulture);
            }
        }
    }
}
