USE [FinanceDB]
GO

/* DROP THE FUNCTION THAT CHECK THE DB SCHEMA AND RETURN PERMISSION STRING */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GetPermission]',N'FN'))
DROP FUNCTION [dbo].[GetPermission]
GO

/* DROP THE TRIGGER [dbo].[ModBalanceAfterTransDel] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ModBalanceAfterTransDel]',N'TR'))
DROP TRIGGER [dbo].[ModBalanceAfterTransDel]
GO

/* DROP THE TRIGGER [dbo].[ModBalanceAfterTransMade] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ModBalanceAfterTransMade]',N'TR'))
DROP TRIGGER [dbo].[ModBalanceAfterTransMade]
GO

/* DROP THE FUNCTION [dbo].[GetCashflowSheet] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[dbo].[GetCashflowSheet]',N'TF'))
DROP FUNCTION [dbo].[dbo].[GetCashflowSheet]
GO

/* DROP THE FUNCTION [dbo].[GetBalanceSheet] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[dbo].[GetBalanceSheet]',N'TF'))
DROP FUNCTION [dbo].[dbo].[GetBalanceSheet]
GO

/* DROP THE FUNCTION [dbo].[GetSchedules] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GetSchedules]',N'TF'))
DROP FUNCTION [dbo].[GetSchedules]
GO

/* DROP THE FUNCTION [dbo].[GetTransactions] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GetTransactions]',N'TF'))
DROP FUNCTION [dbo].[GetTransactions]
GO

/* DROP VIEW [dbo].[ACCOUNTS_LIST] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ACCOUNTS_LIST]',N'V'))
DROP VIEW [dbo].[ACCOUNTS_LIST]
GO

/* DROP FOREIGN KEY PRIOR TO DROP TABLE */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SCHEDULE]',N'U'))
ALTER TABLE [dbo].[SCHEDULE] DROP CONSTRAINT [FK_SCHEDULE_SRC_ACC]
ALTER TABLE [dbo].[SCHEDULE] DROP CONSTRAINT [FK_SCHEDULE_DST_ACC]
ALTER TABLE [dbo].[SCHEDULE] DROP CONSTRAINT [FK_SCHEDULE_CATEGORY]
GO

/* DROP Table [dbo].[SCHEDULE] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SCHEDULE]',N'U'))
DROP TABLE [dbo].[SCHEDULE]
GO

/* DROP FOREIGN KEY PRIOR TO DROP TABLE */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRANSACTION]',N'U'))
ALTER TABLE [dbo].[TRANSACTION] DROP CONSTRAINT [FK_TRANSACTION_SRC_ACC]
ALTER TABLE [dbo].[TRANSACTION] DROP CONSTRAINT [FK_TRANSACTION_DST_ACC]
ALTER TABLE [dbo].[TRANSACTION] DROP CONSTRAINT [FK_TRANSACTION_CATEGORY]
GO

/* DROP Table [dbo].[TRANSACTION] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRANSACTION]',N'U'))
DROP TABLE [dbo].[TRANSACTION]
GO

/* DROP FOREIGN KEY PRIOR TO DROP TABLE */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ACCOUNT]',N'U'))
ALTER TABLE [dbo].[ACCOUNT] DROP CONSTRAINT [FK_ACCOUNT_TYPE]
ALTER TABLE [dbo].[ACCOUNT] DROP CONSTRAINT [FK_ACCOUNT_CURRENCY]
GO

/* DROP Table [dbo].[ACCOUNT] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ACCOUNT]',N'U'))
DROP TABLE [dbo].[ACCOUNT]
GO

/* DROP FOREIGN KEY PRIOR TO DROP TABLE */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CATEGORY]',N'U'))
ALTER TABLE [dbo].[CATEGORY] DROP CONSTRAINT [FK_CATEGORY_PARENT]
GO

/* DROP Table [dbo].[CATEGORY] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CATEGORY]',N'U'))
DROP TABLE [dbo].[CATEGORY]
GO

/* DROP FOREIGN KEY PRIOR TO DROP TABLE */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TYPE]',N'U'))
ALTER TABLE [dbo].[TYPE] DROP CONSTRAINT [FK_TYPE_PARENT]
GO

/* DROP Table [dbo].[TYPE] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TYPE]',N'U'))
DROP TABLE [dbo].[TYPE]
GO

/* DROP Table [dbo].[CURRENCY] */
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CURRENCY]',N'U'))
BEGIN
	DROP TABLE [dbo].[CURRENCY]
END
GO

/* OPTIONS TO SET BEFORE CREATE SCHEMA */
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/* CREATE Table [dbo].[CURRENCY] */
CREATE TABLE [dbo].[CURRENCY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[ACRONYM] [nvarchar](50) NOT NULL,
	[DEC_POINT] [tinyint] NOT NULL,
	[IS_MAIN] [bit] NOT NULL,
 CONSTRAINT [PK_CURRENCY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/* ADD CONSTRAINT Setting DEFAULT VALUE of DEC_POINT in Table [dbo].[CURRENCY] */
ALTER TABLE [dbo].[CURRENCY] ADD  CONSTRAINT [DF_CURRENCY_DEC_POINT]  DEFAULT ((0)) FOR [DEC_POINT]
GO

/* ADD CONSTRAINT Setting DEFAULT VALUE of IS_MAIN in Table [dbo].[CURRENCY] */
ALTER TABLE [dbo].[CURRENCY] ADD  CONSTRAINT [DF_CURRENCY_IS_MAIN]  DEFAULT ((0)) FOR [IS_MAIN]
GO

/* CREATE Table [dbo].[TYPE] */
CREATE TABLE [dbo].[TYPE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PARENT_ID] [bigint] NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](4000) NULL,
	[TYPE_FLAG] [smallint] NOT NULL,
 CONSTRAINT [PK_TYPE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[TYPE] */
ALTER TABLE [dbo].[TYPE]  WITH CHECK ADD  CONSTRAINT [FK_TYPE_PARENT] FOREIGN KEY([PARENT_ID])
REFERENCES [dbo].[TYPE] ([ID])
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[TYPE] */
ALTER TABLE [dbo].[TYPE] CHECK CONSTRAINT [FK_TYPE_PARENT]
GO

/* CREATE Table [dbo].[CATEGORY] */
CREATE TABLE [dbo].[CATEGORY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PARENT_ID] [bigint] NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](4000) NULL,
	[FLOW_DIRECT] [smallint] NOT NULL,
 CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/* ADD CONSTRAINT Setting DEFAULT VALUE of FLOW_DIRECT in Table [dbo].[CATEGORY] */
ALTER TABLE [dbo].[CATEGORY] ADD  CONSTRAINT [DF_CATEGORY_FLOW_DIRECT]  DEFAULT ((0)) FOR [FLOW_DIRECT]
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[CATEGORY] */
ALTER TABLE [dbo].[CATEGORY]  WITH CHECK ADD  CONSTRAINT [FK_CATEGORY_PARENT] FOREIGN KEY([PARENT_ID])
REFERENCES [dbo].[CATEGORY] ([ID])
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[CATEGORY] */
ALTER TABLE [dbo].[CATEGORY] CHECK CONSTRAINT [FK_CATEGORY_PARENT]
GO

/* CREATE Table [dbo].[ACCOUNT] */
CREATE TABLE [dbo].[ACCOUNT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](4000) NULL,
	[TYPE_ID] [bigint] NOT NULL,
	[CURRENCY_ID] [bigint] NOT NULL,
	[CREATE_TIME] [datetime2](7) NOT NULL,
	[UPDATE_TIME] [datetime2](7) NOT NULL,
	[BALANCE] [decimal](15, 3) NOT NULL,
	[DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_ACCOUNT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/* ADD CONSTRAINT Setting DEFAULT VALUE of CREATE_TIME in Table [dbo].[ACCOUNT] */
ALTER TABLE [dbo].[ACCOUNT] ADD  CONSTRAINT [DF_ACCOUNT_CREATE_TIME]  DEFAULT (sysutcdatetime()) FOR [CREATE_TIME]
GO

/* ADD CONSTRAINT Setting DEFAULT VALUE of UPDATE_TIME in Table [dbo].[ACCOUNT] */
ALTER TABLE [dbo].[ACCOUNT] ADD  CONSTRAINT [DF_ACCOUNT_UPDATE_TIME]  DEFAULT (sysutcdatetime()) FOR [UPDATE_TIME]
GO

/* ADD CONSTRAINT Setting DEFAULT VALUE of DELETED in Table [dbo].[ACCOUNT] */
ALTER TABLE [dbo].[ACCOUNT] ADD  CONSTRAINT [DF_ACCOUNT_DELETED]  DEFAULT ((0)) FOR [DELETED]
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[ACCOUNT] */
ALTER TABLE [dbo].[ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK_ACCOUNT_CURRENCY] FOREIGN KEY([CURRENCY_ID])
REFERENCES [dbo].[CURRENCY] ([ID])
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[ACCOUNT] */
ALTER TABLE [dbo].[ACCOUNT] CHECK CONSTRAINT [FK_ACCOUNT_CURRENCY]
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[ACCOUNT] */
ALTER TABLE [dbo].[ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK_ACCOUNT_TYPE] FOREIGN KEY([TYPE_ID])
REFERENCES [dbo].[TYPE] ([ID])
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[ACCOUNT] */
ALTER TABLE [dbo].[ACCOUNT] CHECK CONSTRAINT [FK_ACCOUNT_TYPE]
GO

/* CREATE Table [dbo].[TRANSACTION] */
CREATE TABLE [dbo].[TRANSACTION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CATEGORY_ID] [bigint] NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](4000) NULL,
	[MADE_TIME] [datetime2](7) NOT NULL,
	[SRC_ACC_ID] [bigint] NULL,
	[SRC_AMOUNT] [decimal](15, 3) NULL,
	[DST_ACC_ID] [bigint] NULL,
	[DST_AMOUNT] [decimal](15, 3) NULL,
	[DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_TRANSACTION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/* ADD CONSTRAINT Setting DEFAULT VALUE of CREATE_TIME in Table [dbo].[ACCOUNT] */
ALTER TABLE [dbo].[TRANSACTION] ADD  CONSTRAINT [DF_TRANSACTION_MADE_TIME]  DEFAULT (sysutcdatetime()) FOR [MADE_TIME]
GO

/* ADD CONSTRAINT Setting DEFAULT VALUE of DELETED in Table [dbo].[TRANSACTION] */
ALTER TABLE [dbo].[TRANSACTION] ADD  CONSTRAINT [DF_TRANSACTION_DELETED]  DEFAULT ((0)) FOR [DELETED]
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[TRANSACTION] */
ALTER TABLE [dbo].[TRANSACTION]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACTION_CATEGORY] FOREIGN KEY([CATEGORY_ID])
REFERENCES [dbo].[CATEGORY] ([ID])
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[TRANSACTION] */
ALTER TABLE [dbo].[TRANSACTION] CHECK CONSTRAINT [FK_TRANSACTION_CATEGORY]
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[TRANSACTION] */
ALTER TABLE [dbo].[TRANSACTION]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACTION_DST_ACC] FOREIGN KEY([DST_ACC_ID])
REFERENCES [dbo].[ACCOUNT] ([ID])
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[TRANSACTION] */
ALTER TABLE [dbo].[TRANSACTION] CHECK CONSTRAINT [FK_TRANSACTION_DST_ACC]
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[TRANSACTION] */
ALTER TABLE [dbo].[TRANSACTION]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACTION_SRC_ACC] FOREIGN KEY([SRC_ACC_ID])
REFERENCES [dbo].[ACCOUNT] ([ID])
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[TRANSACTION] */
ALTER TABLE [dbo].[TRANSACTION] CHECK CONSTRAINT [FK_TRANSACTION_SRC_ACC]
GO

/* CREATE Table [dbo].[SCHEDULE] */
USE [FinanceDB]
GO

/****** Object:  Table [dbo].[SCHEDULE]    Script Date: 2025/07/05 17:19:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SCHEDULE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CATEGORY_ID] [bigint] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](4000) NULL,
	[PERIOD_IN_DAYS] [smallint] NOT NULL,
	[LAST_MADE_TIME] [datetime2](7) NULL,
	[SRC_ACC_ID] [bigint] NULL,
	[SRC_AMOUNT] [decimal](15, 3) NULL,
	[DST_ACC_ID] [bigint] NULL,
	[DST_AMOUNT] [decimal](15, 3) NULL,
	[DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_SCHEDULE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/* ADD CONSTRAINT Setting DEFAULT VALUE of PERIOD_IN_DAYS in Table [dbo].[SCHEDULE] */
ALTER TABLE [dbo].[SCHEDULE] ADD  CONSTRAINT [DF_SCHEDULE_PERIOD_IN_DAYS]  DEFAULT ((0)) FOR [PERIOD_IN_DAYS]
GO

/* ADD CONSTRAINT Setting DEFAULT VALUE of DELETED in Table [dbo].[SCHEDULE] */
ALTER TABLE [dbo].[SCHEDULE] ADD  CONSTRAINT [DF_SCHEDULE_DELETED]  DEFAULT ((0)) FOR [DELETED]
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[SCHEDULE] */
ALTER TABLE [dbo].[SCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_SCHEDULE_CATEGORY] FOREIGN KEY([CATEGORY_ID])
REFERENCES [dbo].[CATEGORY] ([ID])
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[SCHEDULE] */
ALTER TABLE [dbo].[SCHEDULE] CHECK CONSTRAINT [FK_SCHEDULE_CATEGORY]
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[SCHEDULE] */
ALTER TABLE [dbo].[SCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_SCHEDULE_DST_ACC] FOREIGN KEY([DST_ACC_ID])
REFERENCES [dbo].[ACCOUNT] ([ID])
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[SCHEDULE] */
ALTER TABLE [dbo].[SCHEDULE] CHECK CONSTRAINT [FK_SCHEDULE_DST_ACC]
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[SCHEDULE] */
ALTER TABLE [dbo].[SCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_SCHEDULE_SRC_ACC] FOREIGN KEY([SRC_ACC_ID])
REFERENCES [dbo].[ACCOUNT] ([ID])
GO

/* ADD CONSTRAINT Setting FOREIGN KEY on Table [dbo].[SCHEDULE] */
ALTER TABLE [dbo].[SCHEDULE] CHECK CONSTRAINT [FK_SCHEDULE_SRC_ACC]
GO

/* CREATE VIEW [dbo].[ACCOUNTS_LIST] */
CREATE VIEW [dbo].[ACCOUNTS_LIST]
AS
SELECT A.[ID] AS [ID]
      ,B.[ID] AS [TYPE_ID]
      ,C.[ID] AS [CURRENCY_ID]
	  ,C.[IS_MAIN] AS [IS_MAIN]
	  ,B.[TYPE_FLAG] AS [TYPE_FLAG]
      ,A.[NAME] AS [ACCOUNT_NAME]
      ,A.[DESCRIPTION] AS [ACCOUNT_DESC]
      ,B.[NAME] AS [ACCOUNT_TYPE]
      ,C.[ACRONYM] AS [CURRENCY_ACRONYM]
      ,CONVERT(DATETIME2,SWITCHOFFSET(CONVERT(DATETIMEOFFSET,A.[CREATE_TIME]),DATENAME(TzOffset, SYSDATETIMEOFFSET()))) AS [CREATE_TIME]
      ,CONVERT(DATETIME2,SWITCHOFFSET(CONVERT(DATETIMEOFFSET,A.[UPDATE_TIME]),DATENAME(TzOffset, SYSDATETIMEOFFSET()))) AS [UPDATE_TIME]
      ,A.[BALANCE] AS [BALANCE]
	  ,C.[DEC_POINT] AS [DEC_POINT]
  FROM (([dbo].[ACCOUNT] A LEFT JOIN [dbo].[TYPE] B ON A.[TYPE_ID]=B.[ID]) LEFT JOIN [dbo].[CURRENCY] C ON A.[CURRENCY_ID]=C.[ID]) WHERE A.[DELETED]=0
GO

/* CREATE THE FUNCTION THAT RETURN RECORDS OF TABLE [dbo].[TRANSACTION] ACCORDING TO Parameters */
CREATE FUNCTION [dbo].[GetTransactions] 
(
	@ParamAccID BIGINT,
	@ParamCurID BIGINT,
	@ParamStTime DATETIME2,
	@ParamEdTime DATETIME2,
	@ParamCount BIGINT
)
RETURNS 
@TransactionTable TABLE([ID] BIGINT,[CatID] BIGINT,[CatFlow] SMALLINT,[SrcAccID] BIGINT,[SrcAccFlag] SMALLINT,[DstAccID] BIGINT,[DstAccFlag] SMALLINT,[IsSameCur] BIT,[TransName] NVARCHAR(50),[TransDesc] NVARCHAR(4000),[CategoryName] NVARCHAR(50),[MadeTime] DATETIME2,[SrcAccName] NVARCHAR(50),[SrcAmount] DECIMAL(15,3),[SrcDecPnt] TINYINT,[DstAccName] NVARCHAR(50),[DstAmount] DECIMAL(15,3),[DstDecPnt] TINYINT)
AS
BEGIN
	DECLARE @acc2Show TABLE([ID] BIGINT, [Name] NVARCHAR(50), [CurID] BIGINT, [TypeFlag] SMALLINT);
	DECLARE @cat2Show TABLE([ID] BIGINT, [Name] NVARCHAR(50), [FlowDirect] SMALLINT);
	INSERT INTO @acc2Show VALUES(0,N'',0, 0);
	INSERT INTO @acc2Show SELECT A.[ID],A.[NAME],A.[CURRENCY_ID],B.[TYPE_FLAG] FROM [dbo].[ACCOUNT] A LEFT JOIN [dbo].[TYPE] B ON A.[TYPE_ID]=B.[ID];
	INSERT INTO @cat2Show SELECT [ID],[NAME],[FLOW_DIRECT] FROM [dbo].[CATEGORY];
	DECLARE @TransID BIGINT,@CatID BIGINT,@SrcAccID BIGINT,@DstAccID BIGINT,@SrcCurID BIGINT,@DstCurID BIGINT,@SrcDecPnt TINYINT,@DstDecPnt TINYINT;
	DECLARE @IsSameCur BIT,@MadeTime DATETIME2,@SrcAmount DECIMAL(15,3),@DstAmount DECIMAL(15,3);
	DECLARE @CatFlow SMALLINT,@SrcAccFlag SMALLINT,@DstAccFlag SMALLINT, @ToInsert BIT, @CountInserted BIGINT;
	DECLARE @TransName NVARCHAR(50),@SrcAccName NVARCHAR(50),@DstAccName NVARCHAR(50),@CatName NVARCHAR(50),@TransDesc NVARCHAR(4000);
	SET @CountInserted = 0;
	DECLARE trans_cursor CURSOR FOR SELECT [ID],[CATEGORY_ID],[NAME],[DESCRIPTION],[MADE_TIME],[SRC_ACC_ID],[SRC_AMOUNT],[DST_ACC_ID],[DST_AMOUNT] FROM [dbo].[TRANSACTION] WHERE [DELETED]=0 ORDER BY [MADE_TIME] DESC;
	OPEN trans_cursor;  
	FETCH NEXT FROM trans_cursor INTO @TransID,@CatID,@TransName,@TransDesc,@MadeTime,@SrcAccID,@SrcAmount,@DstAccID,@DstAmount;
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		SET @SrcAccName=N''; SET @DstAccName=N''; SET @SrcCurID=NULL; SET @DstCurID=NULL; SET @SrcAccFlag=NULL; SET @DstAccFlag=NULL; SET @IsSameCur=0; SET @SrcDecPnt=NULL; SET @DstDecPnt=NULL;
		SET @ToInsert = 1;
		SELECT @CatName=[NAME],@CatFlow=[FlowDirect] FROM @cat2Show WHERE [ID]=@CatID;
		IF @SrcAccID IS NOT NULL
		BEGIN
			SELECT @SrcAccName=[Name],@SrcCurID=[CurID],@SrcAccFlag=[TypeFlag] FROM @acc2Show WHERE [ID]=@SrcAccID;
			SELECT @SrcDecPnt=[DEC_POINT] FROM [dbo].[CURRENCY] WHERE [ID]=@SrcCurID;
		END
		IF @DstAccID IS NOT NULL
		BEGIN
			SELECT @DstAccName=[Name],@DstCurID=[CurID],@DstAccFlag=[TypeFlag] FROM @acc2Show WHERE [ID]=@DstAccID;
			SELECT @DstDecPnt=[DEC_POINT] FROM [dbo].[CURRENCY] WHERE [ID]=@DstCurID;
		END
		IF @SrcCurID=@DstCurID SET @IsSameCur=1;
		IF @ToInsert = 1	/* Check Account ID IF NOT 0 */
		BEGIN
			IF @ParamAccID IS NULL 
			BEGIN
				IF @SrcAccID IS NOT NULL AND @DstAccID IS NOT NULL SET @ToInsert = 0;
			END
			ELSE
			BEGIN
				IF @ParamAccID<>0 AND @SrcAccID<>@ParamAccID AND @DstAccID<>@ParamAccID SET @ToInsert = 0;
			END
		END
		IF @ToInsert = 1	/* Check Currency ID IF NOT NULL */
		BEGIN
			IF @ParamCurID IS NOT NULL 
			BEGIN
				IF @SrcCurID<>@ParamCurID AND @DstCurID<>@ParamCurID SET @ToInsert = 0;
			END
		END
		IF @ToInsert = 1	/* Check Start Time IF NOT NULL */
		BEGIN
			IF @ParamStTime IS NOT NULL 
			BEGIN
				IF @MadeTime < @ParamStTime SET @ToInsert = 0;
			END
		END
		IF @ToInsert = 1	/* Check End Time IF NOT NULL */
		BEGIN
			IF @ParamEdTime IS NOT NULL 
			BEGIN
				IF @MadeTime > @ParamEdTime SET @ToInsert = 0;
			END
		END
		IF @ToInsert = 1
		BEGIN
			SET @MadeTime = CONVERT(DATETIME2,SWITCHOFFSET(CONVERT(DATETIMEOFFSET,@MadeTime),DATENAME(TzOffset, SYSDATETIMEOFFSET())));
			INSERT INTO @TransactionTable VALUES(@TransID,@CatID,@CatFlow,@SrcAccID,@SrcAccFlag,@DstAccID,@DstAccFlag,@IsSameCur,@TransName,@TransDesc,@CatName,@MadeTime,@SrcAccName,@SrcAmount,@SrcDecPnt,@DstAccName,@DstAmount,@DstDecPnt);
			SET @CountInserted = @CountInserted + 1;
			IF @CountInserted = @ParamCount BREAK;
		END
		FETCH NEXT FROM trans_cursor INTO @TransID,@CatID,@TransName,@TransDesc,@MadeTime,@SrcAccID,@SrcAmount,@DstAccID,@DstAmount;
	END
	CLOSE trans_cursor;  
	DEALLOCATE trans_cursor;
	RETURN
END
GO

/* CREATE THE FUNCTION THAT RETURN RECORDS OF TABLE [dbo].[SCHEDULE] ACCORDING TO Parameters */
CREATE FUNCTION [dbo].[GetSchedules] 
(
	@Filtered BIT
)
RETURNS 
@ScheduleTable TABLE([ID] BIGINT,[CatID] BIGINT,[CatFlow] SMALLINT,[SrcAccID] BIGINT,[SrcAccFlag] SMALLINT,[DstAccID] BIGINT,[DstAccFlag] SMALLINT,[IsSameCur] BIT,[SchedName] NVARCHAR(50),[SchedDesc] NVARCHAR(4000),[CategoryName] NVARCHAR(50),[PeriodInDays] SMALLINT,[LastMadeTime] DATETIME2,[SrcAccName] NVARCHAR(50),[SrcAmount] DECIMAL(15,3),[SrcDecPnt] TINYINT,[DstAccName] NVARCHAR(50),[DstAmount] DECIMAL(15,3),[DstDecPnt] TINYINT)
AS
BEGIN
	DECLARE @acc2Show TABLE([ID] BIGINT, [Name] NVARCHAR(50), [CurID] BIGINT, [TypeFlag] SMALLINT);
	DECLARE @cat2Show TABLE([ID] BIGINT, [Name] NVARCHAR(50), [FlowDirect] SMALLINT);
	INSERT INTO @acc2Show VALUES(0,N'',0, 0);
	INSERT INTO @acc2Show SELECT A.[ID],A.[NAME],A.[CURRENCY_ID],B.[TYPE_FLAG] FROM [dbo].[ACCOUNT] A LEFT JOIN [dbo].[TYPE] B ON A.[TYPE_ID]=B.[ID];
	INSERT INTO @cat2Show SELECT [ID],[NAME],[FLOW_DIRECT] FROM [dbo].[CATEGORY];
	DECLARE @SchedID BIGINT,@CatID BIGINT,@SrcAccID BIGINT,@DstAccID BIGINT,@SrcCurID BIGINT,@DstCurID BIGINT,@SrcDecPnt TINYINT,@DstDecPnt TINYINT;
	DECLARE @IsSameCur BIT,@LastMadeTime DATETIME2,@ChkTime DATETIME2,@SrcAmount DECIMAL(15,3),@DstAmount DECIMAL(15,3);
	DECLARE @CatFlow SMALLINT,@SrcAccFlag SMALLINT,@DstAccFlag SMALLINT,@PeriodInDays SMALLINT,@ToInsert BIT;
	DECLARE @SchedName NVARCHAR(50),@SrcAccName NVARCHAR(50),@DstAccName NVARCHAR(50),@CatName NVARCHAR(50),@SchedDesc NVARCHAR(4000);
	DECLARE sched_cursor CURSOR FOR SELECT [ID],[CATEGORY_ID],[NAME],[DESCRIPTION],[PERIOD_IN_DAYS],[LAST_MADE_TIME],[SRC_ACC_ID],[SRC_AMOUNT],[DST_ACC_ID],[DST_AMOUNT] FROM [dbo].[SCHEDULE] WHERE [DELETED]=0;
	OPEN sched_cursor;  
	FETCH NEXT FROM sched_cursor INTO @SchedID,@CatID,@SchedName,@SchedDesc,@PeriodInDays,@LastMadeTime,@SrcAccID,@SrcAmount,@DstAccID,@DstAmount;
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		SET @ToInsert=1;
		IF @Filtered=1
		BEGIN
			IF @PeriodInDays<=0 SET @ToInsert=0;
			ELSE IF @LastMadeTime IS NULL SET @ToInsert=1;
			ELSE 
			BEGIN
				SET @ChkTime=DATEADD(DAY,@PeriodInDays,@LastMadeTime);
				IF @ChkTime>=SYSUTCDATETIME() SET @ToInsert=0;
			END
		END
		IF @ToInsert=1
		BEGIN
			SET @SrcAccName=N''; SET @DstAccName=N''; SET @SrcCurID=NULL; SET @DstCurID=NULL; SET @SrcAccFlag=NULL; SET @DstAccFlag=NULL; SET @IsSameCur=0; SET @SrcDecPnt=NULL; SET @DstDecPnt=NULL;
			SELECT @CatName=[NAME],@CatFlow=[FlowDirect] FROM @cat2Show WHERE [ID]=@CatID;
			IF @SrcAccID IS NOT NULL
			BEGIN
				SELECT @SrcAccName=[Name],@SrcCurID=[CurID],@SrcAccFlag=[TypeFlag] FROM @acc2Show WHERE [ID]=@SrcAccID;
				SELECT @SrcDecPnt=[DEC_POINT] FROM [dbo].[CURRENCY] WHERE [ID]=@SrcCurID;
			END
			IF @DstAccID IS NOT NULL
			BEGIN
				SELECT @DstAccName=[Name],@DstCurID=[CurID],@DstAccFlag=[TypeFlag] FROM @acc2Show WHERE [ID]=@DstAccID;
				SELECT @DstDecPnt=[DEC_POINT] FROM [dbo].[CURRENCY] WHERE [ID]=@DstCurID;
			END
			IF @SrcCurID=@DstCurID SET @IsSameCur=1;
			SET @LastMadeTime = CONVERT(DATETIME2,SWITCHOFFSET(CONVERT(DATETIMEOFFSET,@LastMadeTime),DATENAME(TzOffset, SYSDATETIMEOFFSET())));
			INSERT INTO @ScheduleTable VALUES(@SchedID,@CatID,@CatFlow,@SrcAccID,@SrcAccFlag,@DstAccID,@DstAccFlag,@IsSameCur,@SchedName,@SchedDesc,@CatName,@PeriodInDays,@LastMadeTime,@SrcAccName,@SrcAmount,@SrcDecPnt,@DstAccName,@DstAmount,@DstDecPnt);
		END
		FETCH NEXT FROM sched_cursor INTO @SchedID,@CatID,@SchedName,@SchedDesc,@PeriodInDays,@LastMadeTime,@SrcAccID,@SrcAmount,@DstAccID,@DstAmount;
	END
	CLOSE sched_cursor;  
	DEALLOCATE sched_cursor;
	RETURN
END
GO

CREATE FUNCTION [dbo].[GetBalanceSheet]
(
	@StTime DATETIME2,
	@EdTime DATETIME2
)
RETURNS
	@BalanceSheet TABLE([CAPTION] NVARCHAR(50),[BALANCE] DECIMAL(15,3),[TYPE_FLAG] SMALLINT,[DEC_POINT] TINYINT)
AS
BEGIN
	DECLARE @CurID BIGINT,@CurAcronym NVARCHAR(50), @CurBalance DECIMAL(15,3), @TypeFlag SMALLINT, @NetBalance DECIMAL(15,3), @InFlow DECIMAL(15,3), @OutFlow DECIMAL(15,3), @NetFlow DECIMAL(15,3), @FlowDirect SMALLINT,@DecPoint TINYINT;
	DECLARE currency_cursor CURSOR FOR SELECT [ID],[ACRONYM],[DEC_POINT] FROM [dbo].[CURRENCY] ORDER BY [IS_MAIN] DESC,[ID] ASC;
	OPEN currency_cursor;
	FETCH NEXT FROM currency_cursor INTO @CurID, @CurAcronym, @DecPoint;
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		/*The purpose of codes between "SET" & "INSERT" is to select total assets in selected currency from ms-sql*/
		INSERT INTO @BalanceSheet([CAPTION],[TYPE_FLAG]) VALUES (@CurAcronym,0);
		SET @CurBalance=0; SET @TypeFlag=0;
		SELECT @CurBalance=SUM(A.[BALANCE]),@TypeFlag=B.[TYPE_FLAG] FROM ([dbo].[ACCOUNT] A LEFT JOIN [dbo].[TYPE] B ON A.[TYPE_ID]=B.[ID])
			LEFT JOIN [dbo].[CURRENCY] C ON A.[CURRENCY_ID]=C.[ID] WHERE C.[ID]=@CurID AND B.[TYPE_FLAG] > 0 GROUP BY B.[TYPE_FLAG],C.[ID];
		IF @TypeFlag=0 SET @TypeFlag=1;
		SET @NetBalance=@CurBalance;
		INSERT INTO @BalanceSheet VALUES (N'  {0}',@CurBalance,@TypeFlag,@DecPoint);
		/*The purpose of codes between "SET" & "INSERT" is to calculate the change in assets*/
		SET @InFlow=0;
		IF @StTime IS NULL
			SET @InFlow=(SELECT SUM(A.[DST_AMOUNT]) FROM (([dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[DST_ACC_ID]=B.[ID]) LEFT JOIN [dbo].[TYPE] C ON B.[TYPE_ID]=C.[ID]) WHERE C.[TYPE_FLAG]>0 AND A.[DELETED]=0 AND B.[CURRENCY_ID]=@CurID);
		ELSE IF @EdTime IS NULL
			SET @InFlow=(SELECT SUM(A.[DST_AMOUNT]) FROM (([dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[DST_ACC_ID]=B.[ID]) LEFT JOIN [dbo].[TYPE] C ON B.[TYPE_ID]=C.[ID]) WHERE C.[TYPE_FLAG]>0 AND A.[DELETED]=0 AND B.[CURRENCY_ID]=@CurID AND A.[MADE_TIME]>=@StTime);
		ELSE
			SET @InFlow=(SELECT SUM(A.[DST_AMOUNT]) FROM (([dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[DST_ACC_ID]=B.[ID]) LEFT JOIN [dbo].[TYPE] C ON B.[TYPE_ID]=C.[ID]) WHERE C.[TYPE_FLAG]>0 AND A.[DELETED]=0 AND B.[CURRENCY_ID]=@CurID AND A.[MADE_TIME]>=@StTime AND A.[MADE_TIME]<@EdTime);
		IF @InFlow IS NULL SET @InFlow=0;
		SET @OutFlow=0;
		IF @StTime IS NULL
			SET @OutFlow=(SELECT SUM(A.[SRC_AMOUNT]) FROM (([dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[SRC_ACC_ID]=B.[ID]) LEFT JOIN [dbo].[TYPE] C ON B.[TYPE_ID]=C.[ID]) WHERE C.[TYPE_FLAG]>0 AND A.[DELETED]=0 AND B.[CURRENCY_ID]=@CurID);
		ELSE IF @EdTime IS NULL
			SET @OutFlow=(SELECT SUM(A.[SRC_AMOUNT]) FROM (([dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[SRC_ACC_ID]=B.[ID]) LEFT JOIN [dbo].[TYPE] C ON B.[TYPE_ID]=C.[ID]) WHERE C.[TYPE_FLAG]>0 AND A.[DELETED]=0 AND B.[CURRENCY_ID]=@CurID AND A.[MADE_TIME]>=@StTime);
		ELSE
			SET @OutFlow=(SELECT SUM(A.[SRC_AMOUNT]) FROM (([dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[SRC_ACC_ID]=B.[ID]) LEFT JOIN [dbo].[TYPE] C ON B.[TYPE_ID]=C.[ID]) WHERE C.[TYPE_FLAG]>0 AND A.[DELETED]=0 AND B.[CURRENCY_ID]=@CurID AND A.[MADE_TIME]>=@StTime AND A.[MADE_TIME]<@EdTime);
		IF @OutFlow IS NULL SET @OutFlow=0;
		IF @InFlow>=@OutFlow
		BEGIN
			SET @NetFlow=@InFlow-@OutFlow;
			SET @FlowDirect=1;
		END
		ELSE
		BEGIN
			SET @NetFlow=@OutFlow-@InFlow;
			SET @FlowDirect=-1;
		END
		INSERT INTO @BalanceSheet VALUES (N'  {0}',@NetFlow,@FlowDirect,@DecPoint);
		/*The purpose of codes between "SET" & "INSERT" is to select total liabilities in selected currency from ms-sql*/
		SET @CurBalance=0; SET @TypeFlag=0;
		SELECT @CurBalance=SUM(A.[BALANCE]),@TypeFlag=B.[TYPE_FLAG]  FROM ([dbo].[ACCOUNT] A LEFT JOIN [dbo].[TYPE] B ON A.[TYPE_ID]=B.[ID])
			LEFT JOIN [dbo].[CURRENCY] C ON A.[CURRENCY_ID]=C.[ID] WHERE C.[ID]=@CurID AND B.[TYPE_FLAG] < 0 GROUP BY B.[TYPE_FLAG],C.[ID];
		IF @TypeFlag=0 SET @TypeFlag=-1;
		INSERT INTO @BalanceSheet VALUES (N'  {0}',@CurBalance,@TypeFlag,@DecPoint);
		/*The purpose of codes between "SET" & "INSERT" is to calculate the change in liabilities*/
		SET @OutFlow=0;
		IF @StTime IS NULL
			SET @OutFlow=(SELECT SUM(A.[DST_AMOUNT]) FROM (([dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[DST_ACC_ID]=B.[ID]) LEFT JOIN [dbo].[TYPE] C ON B.[TYPE_ID]=C.[ID]) WHERE C.[TYPE_FLAG]<0 AND A.[DELETED]=0 AND B.[CURRENCY_ID]=@CurID);
		ELSE IF @EdTime IS NULL
			SET @OutFlow=(SELECT SUM(A.[DST_AMOUNT]) FROM (([dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[DST_ACC_ID]=B.[ID]) LEFT JOIN [dbo].[TYPE] C ON B.[TYPE_ID]=C.[ID]) WHERE C.[TYPE_FLAG]<0 AND A.[DELETED]=0 AND B.[CURRENCY_ID]=@CurID AND A.[MADE_TIME]>=@StTime);
		ELSE
			SET @OutFlow=(SELECT SUM(A.[DST_AMOUNT]) FROM (([dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[DST_ACC_ID]=B.[ID]) LEFT JOIN [dbo].[TYPE] C ON B.[TYPE_ID]=C.[ID]) WHERE C.[TYPE_FLAG]<0 AND A.[DELETED]=0 AND B.[CURRENCY_ID]=@CurID AND A.[MADE_TIME]>=@StTime AND A.[MADE_TIME]<@EdTime);
		IF @OutFlow IS NULL SET @OutFlow=0;
		SET @InFlow=0;
		IF @StTime IS NULL
			SET @InFlow=(SELECT SUM(A.[SRC_AMOUNT]) FROM (([dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[SRC_ACC_ID]=B.[ID]) LEFT JOIN [dbo].[TYPE] C ON B.[TYPE_ID]=C.[ID]) WHERE C.[TYPE_FLAG]<0 AND A.[DELETED]=0 AND B.[CURRENCY_ID]=@CurID);
		ELSE IF @EdTime IS NULL
			SET @InFlow=(SELECT SUM(A.[SRC_AMOUNT]) FROM (([dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[SRC_ACC_ID]=B.[ID]) LEFT JOIN [dbo].[TYPE] C ON B.[TYPE_ID]=C.[ID]) WHERE C.[TYPE_FLAG]<0 AND A.[DELETED]=0 AND B.[CURRENCY_ID]=@CurID AND A.[MADE_TIME]>=@StTime);
		ELSE
			SET @InFlow=(SELECT SUM(A.[SRC_AMOUNT]) FROM (([dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[SRC_ACC_ID]=B.[ID]) LEFT JOIN [dbo].[TYPE] C ON B.[TYPE_ID]=C.[ID]) WHERE C.[TYPE_FLAG]<0 AND A.[DELETED]=0 AND B.[CURRENCY_ID]=@CurID AND A.[MADE_TIME]>=@StTime AND A.[MADE_TIME]<@EdTime);
		IF @InFlow IS NULL SET @InFlow=0;
		IF @InFlow>=@OutFlow
		BEGIN
			SET @NetFlow=@InFlow-@OutFlow;
			SET @FlowDirect=-1;
		END
		ELSE
		BEGIN
			SET @NetFlow=@OutFlow-@InFlow;
			SET @FlowDirect=1;
		END
		INSERT INTO @BalanceSheet VALUES (N'  {0}',@NetFlow,@FlowDirect,@DecPoint);
		/*After this Line Calculate the Equity in selected currency*/
		IF @NetBalance >= @CurBalance
		BEGIN
			SET @NetBalance = @NetBalance - @CurBalance;
			SET @TypeFlag=1;
		END
		ELSE
		BEGIN
			SET @NetBalance = @CurBalance - @NetBalance;
			SET @TypeFlag=-1;
		END
		INSERT INTO @BalanceSheet VALUES (N'  {0}',@NetBalance,@TypeFlag,@DecPoint);
		INSERT INTO @BalanceSheet([CAPTION],[TYPE_FLAG]) VALUES (N'',0);
		FETCH NEXT FROM currency_cursor INTO @CurID, @CurAcronym, @DecPoint;
	END
	CLOSE currency_cursor;  
	DEALLOCATE currency_cursor;
	RETURN;
END
GO

CREATE FUNCTION [dbo].[GetCashflowSheet]
(
	@StTime DATETIME2,
	@EdTime DATETIME2
)
RETURNS
	@CashflowSheet TABLE([CAPTION] NVARCHAR(50),[AMOUNT] DECIMAL(15,3),[FLOW_DIRECT] SMALLINT,[DEC_POINT] TINYINT)
AS
BEGIN
	DECLARE @CurID BIGINT,@CurAcronym NVARCHAR(50), @CurFlow DECIMAL(15,3), @FlowDirect SMALLINT, @NetFlow DECIMAL(15,3),@DecPoint TINYINT;
	DECLARE currency_cursor CURSOR FOR SELECT [ID],[ACRONYM],[DEC_POINT] FROM [dbo].[CURRENCY] ORDER BY [IS_MAIN] DESC,[ID] ASC;
	OPEN currency_cursor;
	FETCH NEXT FROM currency_cursor INTO @CurID, @CurAcronym, @DecPoint;
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		INSERT INTO @CashflowSheet([CAPTION],[FLOW_DIRECT]) VALUES (@CurAcronym,0);
		SET @CurFlow=0; SET @FlowDirect=1;
		IF @StTime IS NULL
			SET @CurFlow=(SELECT SUM(A.[DST_AMOUNT]) FROM [dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[DST_ACC_ID]=B.[ID] WHERE A.[DELETED]=0 AND A.[SRC_ACC_ID] IS NULL AND B.CURRENCY_ID=@CurID);
		ELSE IF @EdTime IS NULL
			SET @CurFlow=(SELECT SUM(A.[DST_AMOUNT]) FROM [dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[DST_ACC_ID]=B.[ID] WHERE A.[DELETED]=0 AND A.[SRC_ACC_ID] IS NULL AND B.CURRENCY_ID=@CurID AND A.[MADE_TIME]>=@StTime);
		ELSE
			SET @CurFlow=(SELECT SUM(A.[DST_AMOUNT]) FROM [dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[DST_ACC_ID]=B.[ID] WHERE A.[DELETED]=0 AND A.[SRC_ACC_ID] IS NULL AND B.CURRENCY_ID=@CurID AND A.[MADE_TIME]>=@StTime AND A.[MADE_TIME]<@EdTime);
		IF @CurFlow IS NULL SET @CurFlow=0;
		SET @NetFlow=@CurFlow;
		INSERT INTO @CashflowSheet VALUES (N'  {0}',@CurFlow,@FlowDIrect,@DecPoint);
		SET @CurFlow=0; SET @FlowDirect=-1;
		IF @StTime IS NULL
			SET @CurFlow=(SELECT SUM(A.[SRC_AMOUNT]) FROM [dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[SRC_ACC_ID]=B.[ID] WHERE A.[DELETED]=0 AND A.[DST_ACC_ID] IS NULL AND B.CURRENCY_ID=@CurID);
		ELSE IF @EdTime IS NULL
			SET @CurFlow=(SELECT SUM(A.[SRC_AMOUNT]) FROM [dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[SRC_ACC_ID]=B.[ID] WHERE A.[DELETED]=0 AND A.[DST_ACC_ID] IS NULL AND B.CURRENCY_ID=@CurID AND A.[MADE_TIME]>=@StTime);
		ELSE
			SET @CurFlow=(SELECT SUM(A.[SRC_AMOUNT]) FROM [dbo].[TRANSACTION] A LEFT JOIN [dbo].[ACCOUNT] B ON A.[SRC_ACC_ID]=B.[ID] WHERE A.[DELETED]=0 AND A.[DST_ACC_ID] IS NULL AND B.CURRENCY_ID=@CurID AND A.[MADE_TIME]>=@StTime AND A.[MADE_TIME]<@EdTime);
		IF @CurFlow IS NULL SET @CurFlow=0;
		INSERT INTO @CashflowSheet VALUES (N'  {0}',@CurFlow,@FlowDIrect,@DecPoint);
		SET @FlowDirect=0;
		IF @NetFlow >= @CurFlow
		BEGIN
			SET @NetFlow = @NetFlow - @CurFlow;
			SET @FlowDirect=1;
		END
		ELSE
		BEGIN
			SET @NetFlow = @CurFlow - @NetFlow;
			SET @FlowDirect=-1;
		END
		INSERT INTO @CashflowSheet VALUES (N'  {0}',@NetFlow,@FlowDirect,@DecPoint);
		INSERT INTO @CashflowSheet([CAPTION],[FLOW_DIRECT]) VALUES (N'',0);
		FETCH NEXT FROM currency_cursor INTO @CurID, @CurAcronym, @DecPoint;
	END
	CLOSE currency_cursor;  
	DEALLOCATE currency_cursor;
	RETURN;
END
GO

CREATE TRIGGER [dbo].[ModBalanceAfterTransMade] ON [dbo].[TRANSACTION] AFTER INSERT
AS
BEGIN
	DECLARE @TransTime DATETIME2, @SrcAccID BIGINT, @SrcAmount DECIMAL(15,3), @DstAccID BIGINT, @DstAmount DECIMAL(15,3), @TypeFlag SMALLINT;
	DECLARE trans_cursor CURSOR FOR SELECT [MADE_TIME],[SRC_ACC_ID],[SRC_AMOUNT],[DST_ACC_ID],[DST_AMOUNT] FROM INSERTED;
	OPEN trans_cursor;  
	FETCH NEXT FROM trans_cursor INTO @TransTime,@SrcAccID,@SrcAmount,@DstAccID,@DstAmount;
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @SrcAccID IS NOT NULL
		BEGIN
			SELECT @TypeFlag=B.[TYPE_FLAG] FROM [dbo].[ACCOUNT] A LEFT JOIN [dbo].[TYPE] B ON A.[TYPE_ID]=B.[ID] WHERE A.[ID]=@SrcAccID;
			IF @TypeFlag > 0 UPDATE [dbo].[ACCOUNT] SET [BALANCE]=[BALANCE]-@SrcAmount,[UPDATE_TIME]=@TransTime WHERE [ID]=@SrcAccID;
			ELSE UPDATE [dbo].[ACCOUNT] SET [BALANCE]=[BALANCE]+@SrcAmount,[UPDATE_TIME]=@TransTime WHERE [ID]=@SrcAccID;
		END
		IF @DstAccID IS NOT NULL
		BEGIN
			SELECT @TypeFlag=B.[TYPE_FLAG] FROM [dbo].[ACCOUNT] A LEFT JOIN [dbo].[TYPE] B ON A.[TYPE_ID]=B.[ID] WHERE A.[ID]=@DstAccID;
			IF @TypeFlag > 0 UPDATE [dbo].[ACCOUNT] SET [BALANCE]=[BALANCE]+@DstAmount,[UPDATE_TIME]=@TransTime WHERE [ID]=@DstAccID;
			ELSE UPDATE [dbo].[ACCOUNT] SET [BALANCE]=[BALANCE]-@DstAmount,[UPDATE_TIME]=@TransTime WHERE [ID]=@DstAccID;
		END
		FETCH NEXT FROM trans_cursor INTO @TransTime,@SrcAccID,@SrcAmount,@DstAccID,@DstAmount;
	END
	CLOSE trans_cursor;  
	DEALLOCATE trans_cursor;
END
GO

CREATE TRIGGER [dbo].[ModBalanceAfterTransDel] ON [dbo].[TRANSACTION] AFTER UPDATE
AS
BEGIN
	DECLARE @TransTime DATETIME2, @SrcAccID BIGINT, @SrcAmount DECIMAL(15,3), @DstAccID BIGINT, @DstAmount DECIMAL(15,3), @TypeFlag SMALLINT, @IsDeleted BIT;
	DECLARE trans_cursor CURSOR FOR SELECT [MADE_TIME],[SRC_ACC_ID],[SRC_AMOUNT],[DST_ACC_ID],[DST_AMOUNT],[DELETED] FROM INSERTED;
	OPEN trans_cursor;
	FETCH NEXT FROM trans_cursor INTO @TransTime,@SrcAccID,@SrcAmount,@DstAccID,@DstAmount,@IsDeleted;
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF @IsDeleted=1
		BEGIN
			IF @SrcAccID IS NOT NULL
			BEGIN
				SELECT @TypeFlag=B.[TYPE_FLAG] FROM [dbo].[ACCOUNT] A LEFT JOIN [dbo].[TYPE] B ON A.[TYPE_ID]=B.[ID] WHERE A.[ID]=@SrcAccID;
				IF @TypeFlag > 0 UPDATE [dbo].[ACCOUNT] SET [BALANCE]=[BALANCE]+@SrcAmount,[UPDATE_TIME]=@TransTime WHERE [ID]=@SrcAccID;
				ELSE UPDATE [dbo].[ACCOUNT] SET [BALANCE]=[BALANCE]-@SrcAmount,[UPDATE_TIME]=@TransTime WHERE [ID]=@SrcAccID;
			END
			IF @DstAccID IS NOT NULL
			BEGIN
				SELECT @TypeFlag=B.[TYPE_FLAG] FROM [dbo].[ACCOUNT] A LEFT JOIN [dbo].[TYPE] B ON A.[TYPE_ID]=B.[ID] WHERE A.[ID]=@DstAccID;
				IF @TypeFlag > 0 UPDATE [dbo].[ACCOUNT] SET [BALANCE]=[BALANCE]-@DstAmount,[UPDATE_TIME]=@TransTime WHERE [ID]=@DstAccID;
				ELSE UPDATE [dbo].[ACCOUNT] SET [BALANCE]=[BALANCE]+@DstAmount,[UPDATE_TIME]=@TransTime WHERE [ID]=@DstAccID;
			END
		END
		FETCH NEXT FROM trans_cursor INTO @TransTime,@SrcAccID,@SrcAmount,@DstAccID,@DstAmount,@IsDeleted;
	END
	CLOSE trans_cursor;  
	DEALLOCATE trans_cursor;
END
GO

/* CREATE THE FUNCTION THAT CHECK THE DB SCHEMA AND RETURN PERMISSION STRING */
CREATE FUNCTION [dbo].[GetPermission]()
RETURNS NVARCHAR(10)
AS
BEGIN
	DECLARE @obj2Chk TABLE(OBJ_SN TINYINT, OBJ_ID NVARCHAR(50), OBJ_TYPE NVARCHAR(10), OBJ_FOUND TINYINT, ROW_COUNT BIGINT);
	INSERT INTO @obj2Chk VALUES(0,N'[dbo].[CURRENCY]',N'U',0,0);
	INSERT INTO @obj2Chk VALUES(1,N'[dbo].[TYPE]',N'U',0,0);
	INSERT INTO @obj2Chk VALUES(2,N'[dbo].[CATEGORY]',N'U',0,0);
	INSERT INTO @obj2Chk VALUES(3,N'[dbo].[ACCOUNT]',N'U',0,0);
	INSERT INTO @obj2Chk VALUES(4,N'[dbo].[TRANSACTION]',N'U',0,0);
	INSERT INTO @obj2Chk VALUES(5,N'[dbo].[SCHEDULE]',N'U',0,0);
	INSERT INTO @obj2Chk VALUES(6,N'[dbo].[ACCOUNTS_LIST]',N'V',0,0);
	INSERT INTO @obj2Chk VALUES(7,N'[dbo].[GetTransactions]',N'TF',0,0);
	INSERT INTO @obj2Chk VALUES(8,N'[dbo].[GetSchedules]',N'TF',0,0);
	INSERT INTO @obj2Chk VALUES(9,N'[dbo].[dbo].[GetBalanceSheet]',N'TF',0,0);
	INSERT INTO @obj2Chk VALUES(10,N'[dbo].[dbo].[GetCashflowSheet]',N'TF',0,0);
	INSERT INTO @obj2Chk VALUES(11,N'[dbo].[ModBalanceAfterTransMade]',N'TR',0,0);
	INSERT INTO @obj2Chk VALUES(12,N'[dbo].[ModBalanceAfterTransDel]',N'TR',0,0);
	DECLARE obj_cursor CURSOR FOR SELECT OBJ_ID,OBJ_TYPE FROM @obj2Chk;  
	OPEN obj_cursor;  
	DECLARE @objID NVARCHAR(50), @objType NVARCHAR(10), @retVal NVARCHAR(10);
	FETCH NEXT FROM obj_cursor INTO @objID, @objType;
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(@objID,@objType))
		BEGIN
			UPDATE @obj2Chk SET OBJ_FOUND=1 WHERE OBJ_ID=@objID;
			IF @objType=N'U'
				UPDATE @obj2Chk SET	ROW_COUNT=(SELECT SUM(row_count) FROM sys.dm_db_partition_stats DPS
					WHERE DPS.object_id = OBJECT_ID(@objID,@objType))
					WHERE OBJ_ID=@objID;
		END
		FETCH NEXT FROM obj_cursor INTO @objID, @objType;
	END
	CLOSE obj_cursor;  
	DEALLOCATE obj_cursor;
	IF (SELECT COUNT(*) FROM @obj2Chk WHERE OBJ_FOUND=0) > 0 SET @retVal=NULL
	ELSE IF (SELECT COUNT(*) FROM @obj2Chk WHERE ROW_COUNT>0 AND OBJ_SN<4) = 4 SET @retVal = N'1111111'
	ELSE IF (SELECT COUNT(*) FROM @obj2Chk WHERE ROW_COUNT>0 AND OBJ_SN<2) = 2 SET @retVal = N'1011110'
	ELSE SET @retVal = N'1010110';
	RETURN @retVal;
END
GO
